### ISSUE TITLE
Install problems

### ISSUE THREAD

**Issue by FWillems** [leahoswald/lovelace-dwd-pollenprognose-card#1]
I'm having some problems to install this very nice integartion. Can you or some else please help me? 

After installing there is no possibility to see any card in my lovelace ui. I can add a card, but this doesnt show anything...

Info to what i have already done
- copied the fil _pollenprognose-card.js_ to my www folder
- copied _pollen_img_ folder to my www folder
- added /local/pollenprognose-card.js to my Ressourcen 
- rebooted home assitant
- reloaded the webpage with F12 refresh
- added
_type: custom:pollenprognose-card
region_desc: Oberrhein und unteres Neckartal
region_id: 111
allergens:
  - Birke_
- rebooted home assitant
- reloaded the webpage with F12 refresh

Does anbody know what i'm doing wrong?
Thank You!!!

**Comment by leahoswald** [comment]
That should work and looks right for me. Do you have installed the dwd pollen integration this card needs?

**Comment by FWillems** [comment]
Hi, first off all, thank you for help. Yes, I have installed the dwd pollen integration. This integration is working fine. I get 1 integration with 8 entities and values in between 0 and actually 3 for each entity like "ambrosia". But checking that I was wondering, may it be a problem, that I have renamed the sensors of the dwd integration? My sensors are named as follows
- sensor.pollen_ambrosia
- sensor.pollen_beifuss
- etc 

Thank you!

**Comment by leahoswald** [comment]
Jup, thats the problem. The card expects the default sensor names by the dwd pollen integration.

**Comment by FWillems** [comment]
Thank you very much! The intergration is working very fine as long as you don't touch the dwd pollen sensor names....

Its looking great! Nice work!!!!

![grafik](https://user-images.githubusercontent.com/17938869/163406507-5c24ff94-d40d-44d9-a1f5-e3bdd04a0b12.png)
